version: '3.3'

services:
  web:
    image: nginx:latest

    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - html:/var/www/html
    networks:
      - code-network
    links:
      - prestashop
    ports:
      - 80:80
  db:
    image: mariadb
    container_name: mariadb
    command: --max_allowed_packet=1G
    environment:
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - UPLOAD_LIMIT=1024M
      

    networks:
      - code-network
    volumes:
      - db:/var/lib/mysql
      - html:/home/prestashop/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - pma_arbitrary=1
      - pma_host=mariadb
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - code-network

  prestashop:
    build: ./prestashop
    image: prestashop-1.7
    container_name: prestashop-1.7-fpm
    environment:
      - PS_DEMO_MODE=0
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_FOLDER_ADMIN=admin_
      - PS_FOLDER_INSTALL=install_
      - TZ=Europe/Paris
      - PHP_MEMORY_LIMIT=2048M
    networks:
      - code-network
    volumes:
      - html:/var/www/html
  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - html:/home/prestashop/
    networks:
      - code-network
    ports:
      - "22:22"
    command: prestashop:prestashop:1001

networks:
  code-network:
    driver: bridge

volumes:
  html:
  db:


