name: PRS170_10

display_name: PRS170_10

version: 1.0.0

author:

  name: "TemplateTrip"

  email: "support@templatetrip.com"

  url: "http://www.templatetrip.com"



meta:

  compatibility:

      from: 1.7.0.0

      to: ~



  available_layouts:

    layout-full-width:

      name: Full Width

      description: No side columns, ideal for distraction-free pages such as product pages.

    layout-both-columns:

      name: Three Columns

      description: One large central column and 2 side columns.

    layout-left-column:

      name: Two Columns, small left column

      description: Two columns with a small left column

    layout-right-column:

      name: Two Columns, small right column

      description: Two columns with a small right column



assets:

  # If you're using this theme as child and you want to load

  # the parent theme assets, uncomment this line.

#  use_parent_assets: true



  # The following lines are showing how to load assets in your page

  # Uncomment and change value to start loading css or js files

  css:

#    all:

#      - id: custom-lib-style

#        path: assets/css/custom-lib.css

#    product:

#      - id: product-style

#        path: assets/css/product.css

#        media: all

#        priority: 200

    all:

      - id: lightbox-style

        path: assets/css/lightbox.css

        priority: 190

  js:

    all:

      - id: owl-lib

        path: assets/js/owl.carousel.min.js

        priority: 310

      - id: cookie-lib

        path: assets/js/jquery.cookie.js

        priority: 320

      - id: zoom-lib

        path: assets/js/jquery.zoom.min.js

        priority: 330

    index:

      - id: lightbox-lib

        path: assets/js/lightbox-2.6.min.js

        priority: 330

global_settings:

  configuration:

    PS_IMAGE_QUALITY: png

  modules:

   to_enable:

     - ps_linklist

     - ttbestsellers

     - ttfeaturedproducts

     - ttnewproducts

     - ttspecials

     - smartblog

     - smartbloghomelatestnews

     - ttcompare

     - ttproductwishlist

     - ttproductcomments

     - ttproductimagehover

     - ttblocksearch

     - ttproductcountdown

     - ttcmsservices

     - ttcmsbottombanner
     
     - ttbrandlogo

     - ttcmstopbanner   

     - ttmegamenu

     - tttoplink

     - ttbottomlink

     - ttcmsheader

     - ttcmsheaderservices
     
     - ttcategoryslider
     
     - ec_customeraccountlinks	
   to_disable:

     - ps_featuredproducts

     - ps_customtext

     - ps_banner 
     
     - ps_imageslider

     - ps_customeraccountlinks
     
     - ps_advertising

  hooks:

    custom_hooks:

      - name: displayHomeTab

        title: Hometab content

        description: Add a widget area above the footera

      - name: displayTopColumn

        title: TopColumn content

        description: Add a widget area above the content

      - name: displayTopColumnAfter

        title: TopColumnAfter content

        description: Add a widget area after the top column

    modules_to_hook:

      displayNav1:

        - ttcmsheader

        - ps_contactinfo

      displayNav2:

        - ttcmsheaderservices

        - ttblocksearch

      displayTop:

        - ttmegamenu

        - tttoplink

        - ps_shoppingcart

        - ps_customersignin

        - ps_currencyselector

        - ps_languageselector

      displayTopColumn:
       
        - ttcmsrightbanner

      displayHomeTab:

        - ttnewproducts
        
        - ttfeaturedproducts
    

      displayHome:

        - ttcmsbanner
                
        - ttcategoryslider

        - ttbestsellers  
        
                        
        
      displayFooterBefore:

        - ttbrandlogo  

      displayFooter:
      
        - ps_linklist

        - ec_customeraccountlinks

        - ps_contactinfo

        - ps_socialfollow
        
        - ttcmspaymentlogo

      displayLeftColumn:

        - ec_categorytree

        - ps_facetedsearch

        - ps_specials

      displayLeftColumnProduct:

        - ps_categorytree

        - ps_facetedsearch

      displayRightColumn:

        - ps_specials

        - ttcmsrightbottombanner

        - ps_advertising
   
      displayRightColumnProduct:

        - ttcmsservices

        - ttcmsrightbottombanner

      displaySearch:

        - ps_searchbar

      displayProductAdditionalInfo:

        - ps_sharebuttons

      displayProductListReviews:

      displayFooterProduct:

      displayReassurance:

        - blockreassurance

      displayOrderConfirmation2:

        - ps_featuredproducts

      displayCrossSellingShoppingCart:

        - ps_featuredproducts



  image_types:

    cart_default:

      width: 100

      height: 120

      scope: [products]

    small_default:

      width: 70

      height: 91

      scope: [products, categories, manufacturers, suppliers]

    medium_default:

      width: 386

      height: 502

      scope: [products, manufacturers, suppliers]

    home_default:

      width: 295

      height: 384

      scope: [products]

    large_default:

      width: 870

      height: 1131

      scope: [products, manufacturers, suppliers]

    category_default:

      width: 965

      height: 250

      scope: [categories]

    stores_default:

      width: 115

      height: 170

      scope: [stores]



theme_settings:

  default_layout: layout-full-width

  layouts:

    index: layout-left-column

    category: layout-left-column

    best-sales: layout-left-column

    new-products: layout-left-column

    prices-drop: layout-left-column

    contact: layout-left-column

    product: layout-left-column

    cms: layout-left-column

    identity: layout-both-column

    module-ttproductwishlist-mywishlist: layout-left-column

    history: layout-left-column

    order-slip: layout-left-column

    addresses: layout-left-column

    stores: layout-left-column

    authentication: layout-left-column

    search: layout-left-column

    module-smartblog-details: layout-left-column

    module-smartblog-category: layout-left-column

    cart: layout-left-column

    sitemap: layout-left-column

    my-account: layout-left-column

    pagenotfound: layout-left-column

    module-ttcompare-compare: layout-left-column

dependencies:

  modules:

    - ttbestsellers

    - ttfeaturedproducts

    - ttnewproducts

    - ttspecials

    - smartblog

    - smartbloghomelatestnews

    - ttcompare

    - ttproductwishlist

    - ttproductcomments

    - ttproductimagehover

    - ttblocksearch

    - ttproductcountdown

    - ttcmsservices

    - ttcmsbottombanner

    - ttcmsbanner

    - ttcmsfooter

    - ttcmspaymentlogo

    - ttcategoryslider

    - ttcategoryfeature

    - ttbrandlogo

    - ttcmsrightbanner

    - ttcmstopbanner

    - tawkto

    - ttpopupnewsletter

    - ttmegamenu

    - tttoplink

    - ttbottomlink

    - ttcmsheader

    - ttcmsheaderservices

    - ttcmsrightbottombanner
    
    - ps_customeraccountlinks
    

